---

- name: Provision a {{ application_name }} server
  hosts: gpuserver
  sudo: yes
  sudo_user: root
  remote_user: root
  vars:
    - nginx_server_name: "adder.totalgood.org"
    - setup_git_repo: yes
    - update_apt_cache: yes
  vars_files:
    - env_vars/base.yml
    - env_vars/dev.yml

  roles:
    - base
    - db
    - web
    - memcached
    - dyndns
    - scipy
