---
- hosts: totalgood.org
  sudo: yes
  vars:
    - ansible_port: 10527
    - ansible_ssh_port: 10527
    - ansible_user: root
    - ansible_ssh_private_key_file: /home/hobs/.ssh/id_rsa
    - nginx_server_name: "adder.totalgood.org"
    - setup_git_repo: yes
    - update_apt_cache: no
  vars_files:
    - env_vars/base.yml
    - env_vars/dev.yml
    - env_vars/hackor.yml
  roles:
    - web
