---
- hosts: totalgood.org
  sudo: yes
  vars:
    - ansible_port: 10527
    - ansible_ssh_port: 10527
    - ansible_user: root
    - ansible_ssh_user: root
    - ansible_ssh_private_key_file: /home/hobs/.ssh/id_rsa
    - nginx_server_name: "adder.totalgood.org"
    - setup_git_repo: yes
    - update_apt_cache: no
  vars_files:
    - vars/base.yml
    - vars/dev.yml
    - vars/hackor.yml
  tasks:
    # pull from origin and delete pyc files
    - include: roles/web/tasks/setup_git_repo.yml
