---

- name: Provision a GPU server with CUDA and keras and scipy
  hosts: all
  sudo: yes
  sudo_user: root
  remote_user: root
  vars_files:
    - env_vars/base.yml
    - env_vars/dev.yml

  roles:
    - scipy
