---

- name: Create a {{ application_name }} virtual machine via vagrant
  hosts: all
  sudo: yes
  sudo_user: root
  remote_user: vagrant
  vars:
    - setup_git_repo: yes
    - update_apt_cache: yes
  vars_files:
    - vars/base.yml
    - vars/dev.yml
    - vars/local.yml

  roles:
    - base
    - db
    - web
    - memcached