---

git_repo: https://github.com/hobson/totalgood

project_name: totalgood
application_name: totalgood
host_fqdn: "adder.totalgood.org"

ssl_dest_dir: /etc/ssl
download_path: /tmp

ssl_crt: "{{ lookup('file', '/home/hobs/.tg.config/totalgood.org.crt') }}"

ssl_key: "{{ lookup('file', '/home/hobs/.tg.config/totalgood.org.key') }}"

ansible_ssh_port: "{{ lookup('env','ANSIBLE_SSH_PORT') }}"
ansible_ssh_user: "{{ lookup('env','ANSIBLE_SSH_USER') }}"
ansible_ssh_private_key_file: "{{ lookup('env','ANSIBLE_SSH_PRIVATE_KEY_FILE') }}"


