---

git_repo: https://github.com/hobson/totalgood

project_name: totalgood
application_name: totalgood

ssl_dest_dir: /etc/ssl

ssl_crt: "{{ lookup('file', '/etc/nginx/ssl/totalgood.org.crt') }}"

ssl_key: "{{ lookup('file', '/etc/nginx/ssl/totalgood.org.key') }}"
