---

git_repo: https://github.com/hobson/totalgood

# Database settings.
db_user: "{{ lookup('env','DATABASE_USER') }}"
db_name: "{{ lookup('env','DATABASE_NAME') }}"
# may be DATABASE_PASSWORD or DB_PASSWORD on production server
db_password: "{{ lookup('env','DATABASE_PASSWORD') }}"

db_dump_url: https://dl.dropboxusercontent.com/u/27181407/
db_dump_filename: hackoregon_dump_2015-10-02
load_db_dump: yes

# Django appl settings.
django_settings_file: "{{ application_name }}.settings"
# may be DJANGO_SECRET or DJANGO_SECRET_KEY on remote prod server:
django_secret_key: "{{ lookup('env','DJANGO_SECRET_KEY') }}"
django_admin_user: "admin"
django_admin_password_hashed: "{{ lookup('env','DJ_ADMIN_PASSWORD_HASHED') }}"


# Gunicorn settings. For the number of workers, a good rule to follow is
# 2 x number of CPUs + 1
gunicorn_num_workers: 3

# Setting this to 1 will restart the Gunicorn process each time
# you make a request, basically reloading the code. Very handy
# when developing. Set to 0 for unlimited requests (default).
gunicorn_max_requests: 0


# Nginx settings.
nginx_server_name: "totalgood.org"


# RabbitMQ settings.
rabbitmq_server_name: "{{ inventory_hostname }}"

rabbitmq_admin_user: admin
rabbitmq_admin_password: "{{ lookup('env','RMQ_ADMIN_PASSWORD') }}"

rabbitmq_application_vhost: "{{ application_name }}"
rabbitmq_application_user: "{{ application_name }}"
rabbitmq_application_password: "{{ lookup('env','RMQ_APP_PASSWORD') }}"


# Celery settings.
celery_num_workers: 2
celery_application_settings_file: settings

# SMTP settings.
smtp_host: smtp.gmail.com
smtp_user: admin@totalgood.com
smtp_password: "{{ lookup('env','GMAIL_TG_PASSWORD') }}"

run_django_syncdb: no
run_django_migrate: yes
run_django_south_migration: no
run_django_collectstatic: yes
django_admin: yes

# web and python paths
virtualenv_path: "/webapps/{{ application_name }}"
project_path: "{{ virtualenv_path }}/{{ project_name }}"

usernames: "{{ lookup('env','TG_USERNAMES') }}"
cuda: no
opencl: no
install_keras: no

# used mainly to build the AMD/ATI Catalyst driver deb package
linux_distribution: "Ubuntu"
linux_distribution_release: "trusty"
