---

# Database settings.
db_user: "{{ application_name }}"
db_name: "{{ application_name }}"
db_password: "{{ lookup('env','DB_PASSWORD') }}"


# Gunicorn settings. For the number of workers, a good rule to follow is
# 2 x number of CPUs + 1
gunicorn_num_workers: 3

# Setting this to 1 will restart the Gunicorn process each time
# you make a request, basically reloading the code. Very handy
# when developing. Set to 0 for unlimited requests (default).
gunicorn_max_requests: 0


# Nginx settings.
nginx_server_name: "{{ inventory_hostname }}"


# RabbitMQ settings.
rabbitmq_server_name: "{{ inventory_hostname }}"

rabbitmq_admin_user: admin
rabbitmq_admin_password: "{{ lookup('env','RMQ_ADMIN_PASSWORD') }}"

rabbitmq_application_vhost: "{{ application_name }}"
rabbitmq_application_user: "{{ application_name }}"
rabbitmq_application_password: "{{ lookup('env','RMQ_APP_PASSWORD') }}"


# Celery settings.
celery_num_workers: 2
celery_application_settings_file: settings


# SMTP settings.
smtp_host: smtp.gmail.com
smtp_user: admin@totalgood.com
smtp_password: "{{ lookup('env','GMAIL_TG_PASSWORD') }}"

# Application settings.
django_settings_file: settings
django_secret_key: "{{ lookup('env','DJ_SECRET_KEY') }}"
django_admin_user: "admin"
django_admin_password_hashed: "{{ lookup('env','DJ_ADMIN_PASSWORD_HASHED') }}"

run_django_syncdb: yes
run_django_migrate: yes
run_django_south_migration: no
run_django_collectstatic: yes
django_admin: yes