---

# - name: "Include gpu playbook iff True == {{ gpu }}"
#   include: gpu/main.yml

- name: Install Cython
  pip: virtualenv={{ virtualenv_path }} name=Cython
  sudo: True

- name: "Install matplotlib requirements"
  apt: name={{ item }} state=latest
  sudo: True
  with_items:
    - libfreetype6-dev
    - libpng12-dev
    - libjpeg-dev
    - libpng++-dev
    - libgtkimageview-dev
    - python-gtk2-dev
    - python-matplotlib

- name: "Install scipy requirements (lapack, BLAS, python-scipy, scikit-learn)"
  apt: name={{ item }} state=latest
  sudo: True
  with_items:
    - libblas-dev
    - gfortran
    - liblapack-dev
    - libhdf5-dev
    - h5utils
    - python-scipy

- name: Install python packages into virtualenv without sudo
  pip: virtualenv={{ virtualenv_path }} name={{ item }}
  with_items:
    - nose
    - numpy
    - pyOpenSSL
    - pytz
    - python-dateutil
    - pandas
    - xlrd
    - Pillow
    - matplotlib
    - fuzzywuzzy
    - python-Levenshtein
    - progressbar2
    - python-slugify
    - scikit-learn
    - h5py
    - ipython

- name: Install keras.io into system site-packages with sudo and pip
  pip: virtualenv={{ virtualenv_path }} name=keras
  sudo: True

- name: Install keras.io into virtualenv without sudo
  pip: virtualenv={{ virtualenv_path }} name={{ item }}
  with_items:
    - keras

- name: create users {{ usernames }}
  user: name={{ item }} state=present groups=admin
  with_items:
    - "{{ usernames }}"

- name: copy the .theanorc file to each user's HOME ({{ usernames }})
  copy: src=files/.theanorc
        dest=/home/{{ item }}/.thenaorc
        owner={{ item }}
        group={{ item }}
  with_items:
    - "{{ usernames }}"
