---

- name: Install Cython
  pip: virtualenv={{ virtualenv_path }} name=Cython
  sudo: True

- name: "Install matplotlib requirements"
  apt: name={{ item }} state=latest
  sudo: True
  with_items:
    - libfreetype6-dev
    - libpng12-dev
    - libjpeg-dev
    - libpng++-dev
    - libgtkimageview-dev
    - python-gtk2-dev
    - python-matplotlib

- name: "Install scipy requirements (lapack, BLAS, python-scipy, scikit-learn)"
  apt: name={{ item }} state=latest
  sudo: True
  with_items:
    - libblas-dev
    - gfortran
    - liblapack-dev
    - libhdf5-dev
    - h5utils
    - python-scipy

- stat: path=~/install_cuda.run
  register: got_cuda

- name: download the CUDA SDK from nVidia
  get_url:
    url=http://developer.download.nvidia.com/compute/cuda/7_0/Prod/local_installers/cuda_7.0.28_linux.run
    dest=~/install_cuda.run
    sha256sum=d1292e9c2bbaddad24c46e0b0d15a7130831bfac0382f7159321f41ae385a5ce
  when: got_cuda.stat.exists == False

- name: run the nVidia CUDA installer
  command: sh ~/install_cuda.run -driver -toolkit -silent chdir=~ creates=/usr/local/cuda-7.0
  sudo: True

- name: Install python packages into virtualenv
  pip: virtualenv={{ virtualenv_path }} name={{ item }}
  with_items:
    - nose
    - numpy
    - pyOpenSSL
    - pytz
    - python-dateutil
    - pandas
    - xlrd
    - Pillow
    - matplotlib
    - fuzzywuzzy
    - python-Levenshtein
    - progressbar2
    - python-slugify
    - scikit-learn
    - h5py
    - keras

- name: Install keras.io
  pip: virtualenv={{ virtualenv_path }} name=keras
  sudo: True