---

- name: "Install lapack openCL, BLAS, python-scipy, scikit-learn system-wide"
  apt: name={{ item }} state=latest
  sudo: True
  with_items:
    - cmake
    - libopencv-ocl-dev
    - python-mako
    - libcheck-isa-perl
    - libblas-dev
    - gfortran
    - liblapack-dev
    - libjpeg-dev
    - libhdf5-dev
    - h5utils
    - python-scipy
    - python-matplotlib

- name: Install Cython
  pip: virtualenv={{ virtualenv_path }} name=Cython
  sudo: True

- name: Install python packages into virtualenv
  pip: virtualenv={{ virtualenv_path }} name={{ item }}
  with_items:
    - Cython
    - nose
    - numpy
    - pyOpenSSL
    - pytz
    - python-dateutil
    - pandas
    - xlrd
    - Pillow
    - matplotlib
    - fuzzywuzzy
    - python-Levenshtein
    - progressbar2
    - python-slugify
    - scikit-learn
    - h5py
    - keras

- name: Install keras.io
  pip: virtualenv={{ virtualenv_path }} name=keras
  sudo: True