---

- name: Install dev packages required by the Django app requirements.txt (gnureadline cffi)
  apt: name={{ item }} update_cache={{ update_apt_cache }} force=yes state=installed
  with_items:
    - libreadline-dev
    - libterm-readline-gnu-perl
    - libreadline6
    - libreadline6-dev
    - libreadline-dev
    - libncurses5
    - libncurses5-dev
    - libmemcached-dev
    - zlib1g-dev
    - libssl-dev
    - libffi-dev
  tags: packages

- name: Install packages required by the Django app inside virtualenv
  pip: virtualenv={{ virtualenv_path }} requirements={{ requirements_file }}

- name: Run the Django syncdb command
  django_manage:
    command: syncdb
    app_path: "{{ application_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: django_environment
  when: run_django_syncdb
  tags: django.syncdb

- name: Run Django migrations
  django_manage:
    command: migrate
    app_path: "{{ application_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: django_environment
  when: run_django_migration
  tags: django.migrate

- name: Create a Djano superuser (for admin interface)
  template: src=initial_data.json.j2 dest="{{ application_path }}/fixtures/initial_data.json" backup=no
  when: django_admin
  tags: django.admin

- name: Run Django collectstatic
  django_manage:
    command: collectstatic
    app_path: "{{ application_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: django_environment
  when: run_django_collectstatic
  tags: django.collectstatic




